# Generated by Django 6.0 on 2025-12-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=100)),
                ('slide_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_prompt', models.TextField()),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('font_color', models.CharField(default='#000000', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='api.carouselproject')),
            ],
            options={
                'ordering': ['slide_number'],
            },
        ),
    ]
