# Generated by Django 6.0 on 2025-12-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='generated_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
