# Generated by Django 6.0 on 2025-12-25 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_slide_generated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
