# Generated by Django 6.0 on 2025-12-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_slide_created_at_slide_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselproject',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/logos/'),
        ),
        migrations.AddField(
            model_name='carouselproject',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/profiles/'),
        ),
    ]
