# Generated by Django 6.0 on 2025-12-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_carouselproject_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselproject',
            name='profile_handle',
            field=models.CharField(blank=True, help_text='Social media handle for @ symbol', max_length=100, null=True),
        ),
    ]
